from __future__ import annotations

import typing


class AgentUI(typing.Protocol):
    """Protocol that both CLI and TUI must implement."""

    def show_user_message(self, text: str, images: list[dict] | None = None) -> None: ...

    def show_assistant_markdown(self, text: str) -> None: ...

    def show_assistant_delta(self, text: str) -> None:
        """Optional: streamed partial assistant text. Callers feature-detect
        with hasattr, so UIs without live streaming may omit this."""
        ...

    def show_thinking(self, text: str) -> None: ...

    def show_tool_call(self, name: str, args: dict, status_line: str, verbose: bool) -> None: ...

    def show_tool_result(self, name: str, result_preview: str, verbose: bool) -> None: ...

    def show_status(self, text: str, style: str = "") -> None: ...

    def show_error(self, text: str) -> None: ...

    def show_iteration(self, n: int) -> None: ...

    def show_compaction(self, before_tokens: int, after_tokens: int) -> None: ...

    def show_context_usage(self, usage_str: str) -> None: ...

    def show_agent_finished(self, reason: str) -> None: ...

    def request_approval(
        self,
        tool_name: str,
        args_json: str,
        diff_preview: str | None,
    ) -> bool: ...

    def show_file_change(self, path: str, action: str, tool: str) -> None: ...

    def show_generated_artifact(self, path: str, media_type: str) -> None: ...

    def show_plan_update(self, items: list[dict]) -> None:
        """Optional: a published plan/checklist (plan_update tool). Callers
        feature-detect with hasattr, so UIs without a plan surface may omit
        this."""
        ...

    def prompt_user_input(self, prompt_text: str) -> str:
        """Raises EOFError or KeyboardInterrupt on exit."""
        ...
